version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: wildlife-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - strapi
    restart: unless-stopped
    networks:
      - wildlife-network

  strapi:
    image: ghcr.io/wildlifeai/wildlife-watcher-backend:main
    restart: unless-stopped
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    depends_on:
      - strapiDB
    networks:
      - wildlife-network

  strapiDB:
    image: postgres:15.10-alpine
    ports:
      - "5432:5432"
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - wildlife-data:/var/lib/postgresql/data/
    networks:
      - wildlife-network

volumes:
  wildlife-data:
    name: wildlife-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/wildlife-watcher-backend/postgres-data

networks:
  wildlife-network:
    driver: bridge
