version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: wildlife-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - strapi
    restart: unless-stopped

  strapi:
    image: ghcr.io/wildlifeai/wildlife-watcher-backend:main
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    depends_on:
      - strapiDB

  strapiDB:
    image: postgres:15.10-alpine
    ports:
      - "5432:5432"
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
